### ISSUE TITLE
Tor isn't loading images

### ISSUE THREAD

**Issue by helenahggj** [Wuemeli/tor-relay-configurator#11]
It's not properly working, and maybe it's time to stop as authorities might be involved next, right?

https://granny.anondrop.net/uploads/2a06b30a4da816bf/armin.gif

**Comment by meow18838** [comment]
hey,thanks for using grannyupload, no idea why it isnt working 🤷 
This is not the repo of tor official thing btw

**Comment by Wuemeli** [comment]
What exactly is going on here, guys?

https://github.com/Wuemeli/LinkDefender/issues/10
