### ISSUE TITLE
These settings cause `DirPort --traffic-limit` line to appear in config

### ISSUE THREAD

**Issue by DeflateAwning** [Wuemeli/tor-relay-configurator#2]
Configuration options:

![image](https://github.com/Wuemeli/tor-relay-configurator/assets/11021263/9263216c-05cd-4d7b-ac73-ad6ae6201b18)

Issue: the following line appears in the configuration file after the script is run:

```
DirPort --traffic-limit
```

**Comment by Wuemeli** [comment]
Hey there,

Thanks for the Issue. I will fix this in the next Update

**Comment by Wuemeli** [comment]
Sorry for the long wait had a lot going. I fixed this Bug and also i will maintain this now
