### ISSUE TITLE
Apt sources aren't updated, so tor is perpetually out-of-date

### ISSUE THREAD

**Issue by DeflateAwning** [Wuemeli/tor-relay-configurator#4]
For Ubuntu, for example, these instructions must be implemented in the script to set the `apt` sources properly: https://support.torproject.org/apt/tor-deb-repo/

**Comment by Wuemeli** [comment]
Hey there,
I will look into that and patch it

**Comment by Wuemeli** [comment]
This is only for Debian right? The script already adds the tor keyring etc. Could you please elaborate?

**Comment by Wuemeli** [comment]
@DeflateAwning

**Comment by DeflateAwning** [comment]
At least for Debian-based distros yeah

**Comment by Wuemeli** [comment]
Should have been fixed
